[package]
name = "vspace"
version = "0.1.0"
edition = "2021"

[lib]
name = "vspace"
crate-type = ["staticlib", "rlib"]

[dependencies]
x86 = "0.43"
log = "0.4"
cxx = "1.0"
env_logger = "*"
node-replication = "0.1.1"
mmap = "0.1.*"
libc = "0.2"

[build-dependencies]
cxx-build = "1.0"